### ISSUE TITLE
Use YAML inventory and group variables files to simplify use of this project

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-manage-user#16]
# 💡 Summary #

I think the use of this project can be enhanced by using a YAML inventory file and group variables stored in the project's root directory, and I think it makes sense to modify the `README.md` instructions to reflect this.

## Motivation and context ##

When I recently used this project to create the credentialed users for our compliance scans, I created an `ansible-manage-user/inventory.yml` file that looked like this:
```yaml
all:
    children:
        openvpn:
            hosts:
                i-0123456789abcdef0:
        freeipa:
            hosts:
                i-0123456789abcdef1:
                i-0123456789abcdef2:
                i-0123456789abcdef3:
```

Note that this more easily allows one to create or destroy the user for a particular group of servers.

I also created an `ansible-manage-user/group_vars` directory, which contain a single file named `all.yml` that looks like:
```yaml
allow_sudo: true
ansible_become: yes
username: abcdef
ssh_public_key: ssh-rsa blahblahblah abcdef
```

With these two files in place, I can run the "create" playbook like this:
```bash
$ AWS_PROFILE=cool-sharedservices-startstopssmsession AWS_SHARED_CREDENTIALS_FILE=~/.aws/production_credentials AWS_DEFAULT_REGION=us-east-1 ansible-playbook --inventory=inventory.yml create/playbook.yml
```
And I can run the "delete" playbook (whose name perturbs me since "destroy" is the opposite of "create") like this:
```bash
$ AWS_PROFILE=cool-sharedservices-startstopssmsession AWS_SHARED_CREDENTIALS_FILE=~/.aws/production_credentials AWS_DEFAULT_REGION=us-east-1 ansible-playbook --inventory=inventory.yml delete/playbook.yml
```

To my mind, these changes make this project quite a bit easier to use.

## Acceptance criteria ##

- [x] The instructions in the `README.md` file are edited to reflect the above changes.
